### ISSUE TITLE
Apply new API endpoints

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#102]
When we have finished the issues
- https://github.com/Pandora-IsoMemo/iso-data/issues/4 
- https://github.com/Pandora-IsoMemo/iso-api/issues/2

which belongs to
- https://github.com/Pandora-IsoMemo/iso-app/issues/69

the next step is to integrate the new endpoints into the app. Currently, the endpoint is used here:
https://github.com/Pandora-IsoMemo/iso-app/blob/958eb5c4a01d2d6f998bcda98d8f48fece654699/R/01-isomemoAPI.R#L1-L22

However, this code is redundant with the code of the *IsoMemo* package already on CRAN:
https://github.com/Pandora-IsoMemo/isomemo-data/blob/614a32d909149d0412972023743b8d5a981a61a1/R/01-getData.R#L53-L74

 That is, it would be best to 
- [x] first, remove the redundant code within the app and apply the functions from the ~IsoMemo~ DataTools package in this app -> #103
- Afterwards, we can update the *IsoMemo* package with new API endpoints.  -> https://github.com/Pandora-IsoMemo/data-tools/issues/53

Thus, the new endpoints would be available for the package on CRAN **and** for the app.
By this, we avoid to do things twice ...

**Comment by arunge** [comment]
@isomemo Summarizing what we discussed today:
Within the UI one will be able to select the new endpoints via 
- a new select Input that will be visible if one selects a new radioButton "ontological schemas". The current endpoint will be available under the name "IsoMemo". 
- This will replace the radioButton "IsoMemo" (1) that is used now.

![image](https://user-images.githubusercontent.com/16759098/221856674-b7546b7a-e876-49db-b6e9-09202433036e.png)

**Comment by isomemo** [comment]
@arunge overall Ok but a couple of comments:

IsoMemo radio button to be renamed "Ontological schemas"

Below this is a new drop-down with the title "Select schema:" (the only entry for this will be "IsoMemo - Humans" (rather than just IsoMemo)

Bewlo this the "Database selection:" option remains as it is now!

**Comment by arunge** [comment]
@isomemo With [version 23.06.2](https://github.com/Pandora-IsoMemo/iso-app/pull/166) on [iso-app beta](https://isomemoapp.com/app/iso-memo-app-beta) the user input to select a schema was added.

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/94cf5c74-f143-4826-b5fe-f40bb85ad9e0)
