### ISSUE TITLE
URGENT bug in Pandora import

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#105]
@arunge in IsoMemo beta app the Pandora data import option is not being populated with data sources

**Comment by arunge** [comment]
@isomemo Could you explain what you mean?

When I am starting the import module online it is possible to select different data files. I just changed the default behavior with a last update. The inputs are empty now when initialized (this was one of the tasks). Or do you mean something else?

![image](https://user-images.githubusercontent.com/16759098/220860112-1bfe6e5d-3fba-422c-ba16-21cd05289c4c.png)

**Comment by isomemo** [comment]
@arunge Ok! Working! Perhaps I just had one instance where populating the entries was slow. 

It would be great if the GPT interface is available for the online beta app soon!
