### ISSUE TITLE
Error in loading data via Pandora skin

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#11]
Loaded the LiVES database using the IsoMemo skin. Then switched to Pandora skin and uploaded an Excel file. Data fields for Excel file were not visible in the interface.

**Comment by jroachell15** [comment]
@isomemo yes I confirm this is an issue. @arunge maybe we can solve this small bug by placing the "reset" function every time the user switch skins?

**Comment by isomemo** [comment]
Thanks! Showing only the most recently uploaded data is the expected behaviour!

**Comment by arunge** [comment]
The restructering of the [dataExplorer](https://github.com/Pandora-IsoMemo/iso-app/blob/main/R/03-dataExplorer.R) that fixes the bug was merged into main and beta branches.
