### ISSUE TITLE
Software crashing with KernelTimeR

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/iso-app#110]
[Domesticated Herbivorous CN S .xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10889149/Domesticated.Herbivorous.CN.S.xlsx)

For the attached file, the software is crashing when in KernelTimeR the "Standard deviation or upper time point" is inserted.
I am using the Beta version 23.3.1.

@arunge

**Comment by arunge** [comment]
@CarloCocozza Could you assist on your inputs here? I used your data and the inputs below in KernelTimeR and the app did not crash when adding (1). The model calculation just finished and a map was plotted in a normal way.

Did you do some other steps before the crash? Can you remember some more details?

![image](https://user-images.githubusercontent.com/16759098/223064926-267e1aa4-981d-4b16-8bff-8f4b170d580e.png)

**Comment by CarloCocozza** [comment]
@arunge There are no inputs. It just crashes when I fill in Min. and Max. Year.

So basically I upload the file, insert Min..Year..95.. and when I also insert Max..Year..95.. the software crashes and I cannot keep going with adding the other options. This only happens in the beta version.

**Comment by CarloCocozza** [comment]
hi @arunge any updates on this? 

I still noticed the same issue. Now this is also present in the regular online version of IsoMemo.

**Comment by arunge** [comment]
Did you use the upload directly from the tab "KernelTimeR" or from the tab "Data"?

If first, than it could be related to the bug
- https://github.com/Pandora-IsoMemo/iso-app/issues/122

I am working on a fix.

**Comment by CarloCocozza** [comment]
@arunge Yes, I did it from KernelTimeR. I will try it from Data.

**Comment by CarloCocozza** [comment]
@arunge 

The issue seems fixed and the import option working. However, the model crashed after a while when it was running. I am not aware whether this was a server problem.
