### ISSUE TITLE
Software crashing when exporting plot

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/iso-app#111]
For the attached datasets, in AverageR the offline version 22.12.3.1 (via Docker) and the online Beta version 23.3.1 crashed when clicking on "Export Plot" button. In normal online version 22.12.3.1 the same bug happened when using OperatoR.

For each model, I used the following inputs:

Dependent variable: δ15N.Collagen     or     IRMS.δ13C.Collagen
Uncertainty(optional) of dep. var.: δ15N.Collagen.unc.        or  IRMS.δ13C.Collagen.unc
Longitude variable: Longitude
Latitude variable: Latitude
Site/ID (optional): Site.Name
Smooth type: planar
No Border correction for pacific
Number of basis functions: 250
Extrapolation behaviour: Linear
No Remove model outliers
No Remove data outliers
No Restrict model area
Yes Bayesian model
No Varying standard error
Number of MCMC iterations: 5000
Number of burnin iterations: 500
Number of MCMC chains: 1
MCMC thinning (keep every x-th sample): 10
Amount of smoothing: 1

Map set on 62 Latitude, -22 Longitude, 75 zoom

Map Centering: 0th meridian
Estimation type: Mean
Yes Show model estimates
Range of colour scale: Max range 16 (for 15N); -11 (for 13C); Min range 4 (for 15N); -23 (for 13C)
Terrestrial
Yes Show locations on map
Yes Set colour and shape of location **marks**
Fixed or variable location mark colour?: fixed
Colour of location marks: 000000
Shape of location marks: 3
No Show map grid
Yes Show map scale
Yes Show north arrow
Yes Show plot title
Yes Show colour scale title
Yes Show colour scale
No Set axis labels
No Set north arrow and scale size and position
Location mark size: 0.8
No Apply convex hull
Yes  Mask / Show output within range of points
Mask radius in km: 200
Display up to max standard error: Max
Colour palette: Red-Yellow-Blue
No Reverse colors
Approximate number of colour levels: 20
No Smooth color transition
Plot resolution (px): 300
No Scale point size by variable
No Add location mark text labels
Center point latitude: Empty
Center point longitude: Empty
Radius (km): 100
Axis title font size: 1
Axis label font size: 1

For OperatoR:

Difference between two previously created maps.
Map Centering: 0th meridian
Estimation type: Mean
Yes Show model estimates
Range of colour scale: Max range 3 Min Range -3
Terrestrial
Yes Show locations on map
No Show map grid
Yes Show map scale
Yes Show north arrow
Yes Show plot title
Yes Show colour scale title
Yes Show colour scale
No Set axis labels
No Set north arrow and scale size and position
Colour palette: Red-Yellow-Blue
No Reverse colors
No Smooth color transition
Approximate number of colour levels: 20
Center point latitude: Empty
Center point longitude: Empty
Radius (km): 100
Axis title font size: 1
Axis label font size: 1

[Domesticated Omnivorous CN S 3500-1000 Bronze age.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10897682/Domesticated.Omnivorous.CN.S.3500-1000.Bronze.age.xlsx)
[Domesticated Omnivorous CN S to 3500 Neolithic.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10897683/Domesticated.Omnivorous.CN.S.to.3500.Neolithic.xlsx)
[Domesticated Omnivorous CN S 0-500 Roman.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10897678/Domesticated.Omnivorous.CN.S.0-500.Roman.xlsx)
[Domesticated Omnivorous CN S 500-1000 Early medieval.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10897679/Domesticated.Omnivorous.CN.S.500-1000.Early.medieval.xlsx)
[Domesticated Omnivorous CN S 1000-0 Iron Age.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10897680/Domesticated.Omnivorous.CN.S.1000-0.Iron.Age.xlsx)
[Domesticated Omnivorous CN S 1000-1500 Late Medieval.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10897681/Domesticated.Omnivorous.CN.S.1000-1500.Late.Medieval.xlsx)

@arunge

**Comment by arunge** [comment]
This was also reported here:
- https://github.com/Pandora-IsoMemo/iso-app/issues/112#issuecomment-1457952792

There is an issue with docker, we are checking what is wrong here. For updates please check: https://github.com/Pandora-IsoMemo/iso-app/issues/112
