### ISSUE TITLE
Wrong address for Docker and new installation instructions

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#115]
@arunge according to the Docker output and also the installation instructions the app is being listened to via the http://0.0.0.0:3838 address

However, I have noticed that the address above does not work in the computer we tested. Instead, for us, the address http://127.0.0.1:3838 works

Does http://0.0.0.0:3838 work for you? If so, why the difference in different computers? Do we need instructions with both addresses?

Also, please update the installation instruction using the annexed file below. Do this for the iso-app and for all other apps. I made the text clearer for non-expert users and listed some of the installation issues we had discussed previously.

[installation.docx](https://github.com/Pandora-IsoMemo/iso-app/files/10934215/installation.docx)

**Comment by isomemo** [comment]
@arunge I just noticed that the end part of the doc file that I shared does not have the correct text. Please use the version below instead.
[installation 2.docx](https://github.com/Pandora-IsoMemo/iso-app/files/10963265/installation.2.docx)

**Comment by arunge** [comment]
Regarding
> Does http://0.0.0.0:3838/ work for you? If so, why the difference in different computers? Do we need instructions with both addresses?

Yes, it does work for us. But `http://127.0.0.1:3838/` is also working. So, for simplicity I will only mention the ip you suggested.

I updated the [install instructions for the isomemo-app](https://github.com/Pandora-IsoMemo/iso-app/wiki/Local-install-instructions) as you suggested with the .docx file. Next, I am updateing the instructions of the other apps, respectively.

**Comment by isomemo** [comment]
@arunge one thing I noticed that the address in the file had an extra space between http:// and 127.0.0.1:3838/
please correct if necessary
