### ISSUE TITLE
Beta app not starting

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#116]
@arunge I tried to run the beta version (to test image export) and got the following error (this has not happened in a long time): 

![image](https://user-images.githubusercontent.com/46485054/224104943-322a64d6-1bfc-438d-87dd-0d980a54acc2.png)

**Comment by arunge** [comment]
@isomemo We had to restart shinyProxy in order to bring the changes regarding [a python installation for Resources](https://github.com/Pandora-IsoMemo/resources/issues/76) online. Now, the app is available again: https://isomemoapp.com/app/iso-memo-app-beta
