### ISSUE TITLE
Fix export image from map display after upgrade to R 4.2.1

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#117]
@arunge See error message concerning a missing package in the screenshot below

![image](https://user-images.githubusercontent.com/46485054/224679825-8a9b0d19-d3bb-4ba0-950b-4040397c1daf.png)

**Comment by arunge** [comment]
@isomemo Yes, this we have to fix because of the upgrade of the R-version as mentioned in:
- https://github.com/Pandora-IsoMemo/data-tools/issues/15#issuecomment-1441974766

**Comment by isomemo** [comment]
@arunge Ok

**Comment by jan-abel-inwt** [comment]
The export function of the leaflet map is re-enabled in the [beta-app](https://pandoraapp.earth/app/iso-memo-app-beta)

![image_720](https://user-images.githubusercontent.com/106665518/228832178-59a8c197-8816-478b-84cf-51b8c2a3bc9a.png)
