### ISSUE TITLE
Potential issues with SpreadR

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#118]
Via E-Mail:

> ... SpreadR is freezing after being run. ...

With test data the issue was not reproducable. I asked for:

> Could you help to narrow down the problem by providing:
> - the data you used,
> - the options you have chosen, especially the inputs that differ from the default values, e.g. you could attach a screenshot.
> 
> Did you use 
> - the main version (https://isomemoapp.com/app/iso-memo-app), or 
> - the beta version (https://isomemoapp.com/app/iso-memo-app-beta), or 
> - a local version (https://github.com/Pandora-IsoMemo/iso-app/wiki/Local-install-instructions), if so which version number?
> 
> Did the app freeze 
> - while calculating, or 
> - directly after finishing the calculation, or 
> - did you press a button (if so which one)?

Information received yet:

> ... still having weird issues on Chrome but in another browser it does now seem to be working. It also seems to be working better on my laptop than my office computer ...

> ... So far they [the models] look fairly different than before.

This is unexpected. We did not change anything regarding the modeling for a very long time (> year). The upgrade from R version 4.1.2 to version 4.2.1 should not change any results. If an upgrade causes problems than most of the times we see 
- error messages, 
- the app is crashing,
- or some features do not work anymore and cause the app to crash when trying to use them.

The reason for this is mostly because some of the used packages are not supported anymore.

**Comment by isomemo** [comment]
@arunge can you please test if this is indeed a browser issue? Steve mentioned that he used Chrome.

**Comment by arunge** [comment]
As discussed, I often use Chrome but there had been no issues. However, Steve's issues seems to be solved:

> Yes thanks! I also figured out why they looked different in some cases- (1) I was including a few points with very late radiocarbon dates ... When I fixed issue 1 the models look very very similar- again with a few real differenes from including more data points. It looks like all is good now- thanks again1
>
> Steve
