### ISSUE TITLE
[MPI_tasks2022]: All graphical models in IsoMemoapp (New) ~1.5 h

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#12]
INWT comments (November 2, 2021):
Option to define how many numbers to be shown after decimal point in the scales of graphs. 1 for maps for the legend, 1 for scatterplot

**Comment by jroachell15** [comment]
@isomemo can you elaborate more on this task please?

**Comment by jroachell15** [comment]
Notes to myself: 
- start with the most important apps
- find where the plot function is, find the input that adjust: 
- [ ] scatter plot function  
- [ ] map legend function

**Comment by jroachell15** [comment]
@isomemo Hi Ricardo, Please elaborate more on this task. What I am imagining is that user can adjust the decimal points in the "map setting" input box: position 1
![image](https://user-images.githubusercontent.com/73887426/180971391-a67d1642-416c-46ff-9e71-8cff50d52134.png)

The decimal point in the scales of the graphs?  Do you mean that scales of the map or position 2? Which map and where is the scatterplot? please be more descriptive and provide screen shots if you can. thanks!

**Comment by isomemo** [comment]
@jroachell15 

This is applicable to the models AverageR, TimeR, SpreadR, KernelR, and KernelTimeR and there are two places where decimal points need to be adjusted.

1) For all these models: after a map is generated one can select a specific point (this only requires that coordinates are entered in "Center point latitude" and "Center point longitude") and an average value plus standard deviation is shown as a legend below the map. 

2) Only for TimeR and KernelTimeR one can create a temporal scatter plot. This is under the option "Plot type" by selecting "Time course". User should be able to select number of decimal points for x and y axes.

**Comment by jroachell15** [comment]
Note to self:

found the lines of code that does this: 
![image](https://user-images.githubusercontent.com/73887426/181450928-cbc40f79-7a28-41eb-a1c6-08f62679577e.png)

next:
- make a user interaction that adjust the values

**Comment by jroachell15** [comment]
@isomemo is there a reason that you want the user to adjust the decimals, or do you think the user would like just 2 or 3 places after the decimal and we hard code it?

In my opinion, the right section is already very crowded, from a UI design perspective, the user would have a hard time finding this new adjustment. Maybe on the right hand side or below the map we can implement this?

**Comment by jroachell15** [comment]
Legend decimal places features:

- [ ] AverageR
- [ ] TimeR
- [ ] SpreadR
- [ ] KernelR 
- [ ] KernelTimeR

Scatter plot decimal adjustment:

- [ ] TimeR 
- [ ] KernelTimeR

**Comment by jroachell15** [comment]
Notes to Jian:
- convert the labels for the x y axis into decimal points:
```
y = pmax(minVal, pmin(maxVal, XPred$Est)) 
plot(y ~ time, type="l", ylim = ylims,
       ylab = independent, xlab = "time", main = mainlab, xaxt = 'n', yaxt = 'n')

my_label <- seq(0,      # Specify axis positions of labels
                            max(y),
                            length = 2)
                              
axis(1,                                     # Manually add x axis tick labels
       at = my_label_positions,
       labels = my_labels)
axis(2,                                     # Manually add y axis tick labels
       at = my_label_positions,
       labels = my_labels)
```

**Comment by jroachell15** [comment]
@isomemo 

I just want to give you my honest opinion from the user interface perspective on this task. The ability to let the user to adjust decimal points is not very useful. (maybe you have other opionion about this), namely because:
- It requires another input box for the user, which already crowds the right side of the interface, causing more confusion for the user
- When you actually look at the `TimeCoursePlot`, the decimal points does not really help much because they are all evenly spaced axis labels, so adding the ability to adjust decimal points is a waste of time and resource that you can allocate to some other tasks:
![image](https://user-images.githubusercontent.com/73887426/186660048-13f95c4a-532a-400b-bb2d-56b9135466eb.png)

so the result will be converting the axis labels 
from `[0, 20000, 40000, 60000, 80000, 100000] `
to `[0.000, 20000.000, 40000.000, 60000.000, 80000.000, 100000.000]` 

Is this the end result you want? if yes, then i will continue to develop this feature.

**Comment by isomemo** [comment]
@jroachell15 as mentioned before there are cases where this is necessary. Yes, having a box for inputting the number of decimal points would be best.

**Comment by jroachell15** [comment]
Note to Jian:
- CODE REVIEW: should move the input box `Input decimal places for map legend` to below the centering point input boxes:
`Input decimal places for map legend`

**Comment by jroachell15** [comment]
@isomemo 

Now the decimal places for map legends are done for all models
![image](https://user-images.githubusercontent.com/73887426/187900820-14e379d3-d602-4ac1-b5bd-79d1a4176e47.png)

as well as decimal places for scatterplot are done for timeR and KerneltimeR:

![image](https://user-images.githubusercontent.com/73887426/187900718-f7aab629-87ba-4fcb-be4b-252dd1886dbb.png)
1) input decimal places for scatter plot

**Comment by arunge** [comment]
However, this update is currently only available on a feature branch, but will be in the beta version soon.

**Comment by arunge** [comment]
With the new (1) [version 22.9.2](https://github.com/Pandora-IsoMemo/iso-app/blob/beta/NEWS.md#mpiisoapp-22092) on the [beta branch](https://isomemoapp.com/app/iso-memo-app-beta) one can adjust decimal places:
- for center estimates (2, 3, 4) in _map_ plots
  - this is only possible if a center is provided (5, 6)

![image](https://user-images.githubusercontent.com/16759098/190635697-e3021be9-636e-4d56-ab54-ee0e1de1681d.png)
![image](https://user-images.githubusercontent.com/16759098/190636650-40b14714-f8ba-423e-a501-de016e6046bb.png)

- for axes labels (1) in _time course_ plots (2)
  - additionally, I added the option to specify the number of labels (4) for each axis (sometimes the space for decimal places becomes to small, reducing the number of labels helps here)

![image](https://user-images.githubusercontent.com/16759098/190637752-3da92b54-f769-4ad4-a051-2126f8503ed1.png)

@isomemo Feel free to test the new feature and please let me know if something should be adjusted. If so feel free to re-open the ticket.
