### ISSUE TITLE
[MPI_2022]: Pandora Iso-app - data tables plus interactive map (Part 1)

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#13]
- [x] #88

- [x] Option to show an empty Interactive map if no database is selected. 

- [x] Option to assign color/size/type of symbol by selecting certain columns in table data (for size numeric for other two user can select a palette and something equivalent for symbols – we have this option already implemented for model maps). 
  - [x] color
      ![image](https://user-images.githubusercontent.com/16759098/208758960-f32d4b52-0acb-4ffd-9e17-b528db54270b.png)
  - [x] size
  - [x] type of symbol

- [x] Option to fix the size of points displayed in interactive (currently point size depends on number of locations with same lat/long). -> https://github.com/Pandora-IsoMemo/iso-app/pull/32

- [x] Option to define size of output image (as in model maps) plus the coordinate range of the output (notice that north arrow and scale would have to remain included if selected by user).

- [x] Option to hide/show Pandora/IsoMemo labels on the top left of the interactive map.

**Comment by jroachell15** [comment]
INWT Original Comments (August 21, 2021):
·       duplicates (option to select the fields, option to choose a measure of similarity [the user needs to know, which is appropriate], option to set a threshold; result: additional column which contains row IDs of possible duplicates): ~ 2-3 days, or ~ 20 h
·       Option to show an empty Interactive map if no database is selected: ~1 h
·       Option to set the size of points displayed in interactive (currently point size depends on number of locations with same lat/long).: ~2 h
·       Option to assign color/size/type of symbol...: we are using leaflet here, which is a different package; quick check shows that it should be possible to implement this with leaflet also, however the effort can be rather high because the implementation is different for this package: ~2-3 days or ~20 h
·       Option to hide/show Pandora/IsoMemo labels (all that is visible should be in the export): ~1 h

**Comment by arunge** [comment]
[Mapping](https://github.com/Pandora-IsoMemo/iso-data/blob/main/inst/mapping/Field_Mapping.csv) that is currently used to combine different sources:

![image](https://user-images.githubusercontent.com/16759098/158357297-26659c98-7045-4705-af40-064cbfbd5876.png)

**Comment by arunge** [comment]
@isomemo We added the following features to the beta version.
> - Option to show an empty Interactive map if no database is selected.
> - Option to hide/show Pandora/IsoMemo labels on the top left of the interactive map.

We are curretnly working on the left features.

**Comment by arunge** [comment]
We [decided](https://github.com/Pandora-IsoMemo/iso-app/issues/24#issuecomment-1104991777) to add optional clustering of data points. The default colour represents the size of clusters instead of the data source.

![image](https://user-images.githubusercontent.com/16759098/167123448-e3569f77-29c6-4d27-b78a-5c09ccb4c492.png)

@isomemo We should discuss if we keep the default or if we use colour by source which would require two different cluster groups.

**Comment by arunge** [comment]
@isomemo I added the option to assign color/size of symbols by selecting certain columns with [version 23.01.01](https://github.com/Pandora-IsoMemo/iso-app/pull/86#issue-1528917736) to the [beta app](https://isomemoapp.com/app/iso-memo-app-beta).

![image](https://user-images.githubusercontent.com/16759098/212871902-31fb1ed9-b2a0-4f31-b7f8-ae1ea7cf63ed.png)

Assigning different symbols is still open. I am currently looking for a simple solution for leaflet maps that is similar to that available for maps in the modelling tabs.

**Comment by arunge** [comment]
With [version 23.04.2](https://github.com/Pandora-IsoMemo/iso-app/pull/130) on [iso-app beta](https://isomemoapp.com/app/iso-memo-app-beta) the option to use symbols on the interactive map is online. However, there is an issue with the legend.  Online the figures for the legend icons cannot be found. This did not happen locally, I will check what is going on here:

![image](https://user-images.githubusercontent.com/16759098/233577114-148eecc3-0a0f-467f-956a-11b4cae2370b.png)

**Comment by arunge** [comment]
To do:

- make option for "fixed" size or symbol more clear:
  ![image](https://user-images.githubusercontent.com/16759098/235732044-4b324cf5-6afa-4988-b5ca-7d8e06a727af.png)

**Comment by isomemo** [comment]
Approved! With fixed being the first option in list and between square brackets.

**Comment by arunge** [comment]
With
> - [x] type of symbol

Now, all [above](https://github.com/Pandora-IsoMemo/iso-app/issues/13#issue-1165011631) features are implemented, see https://github.com/Pandora-IsoMemo/iso-app/issues/148#issuecomment-1540690444.

@isomemo Please feel free to test the updates for the interactive map.

**Comment by arunge** [comment]
Issues had been reported [here](https://github.com/Pandora-IsoMemo/iso-app/issues/161). I am closing this issue.
