### ISSUE TITLE
Cannot export Pandora map

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#131]
@arunge In main version cannot export Pandora map as available from the interactive map tab. See error below.

![image](https://user-images.githubusercontent.com/46485054/231750616-a1392815-4a1b-46c9-abd7-cddef8d50564.png)

**Comment by arunge** [comment]
The main app is now up-to-date with the beta version (1), and the export is also working here (2):

![image](https://user-images.githubusercontent.com/16759098/232854292-69350aa7-00ad-4033-8c75-68a79b3ef473.png)
