### ISSUE TITLE
“Interactive map”. Show/hide administrative names and borders

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#133]
Users can show/hide administrative names and/or borders for different map display options (see figure below).

![image](https://user-images.githubusercontent.com/16759098/195054309-a2e43c62-d268-4f52-a36a-e31887e05ad0.png)

**Comment by arunge** [comment]
- with [version 23.05.2](https://github.com/Pandora-IsoMemo/iso-app/pull/151) on [iso-app beta](https://isomemoapp.com/app/iso-memo-app-beta) map types are grouped by having borders/names or not (#133)
  - additionally, the option to add more maps from different providers: https://leaflet-extras.github.io/leaflet-providers/preview/ was added (1)

@isomemo Please, check the changes regarding the grouped map types and let me know if you would like to change something.

![image](https://user-images.githubusercontent.com/16759098/236189253-b61080f2-5afc-4302-ab23-7937420c1500.png)

**Comment by isomemo** [comment]
@arunge you will have to explain to me how this works. In my beta interface the text "Type the name and click "Add..." is not appearing.

**Comment by arunge** [comment]
Oh, sorry, I forgot to mention that I shifted the description to use other maps into an info field that is displayed when hoovering over "i" . Does the hoovering work in your browser?

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/5b7be117-3793-42ab-b113-03f925323098)
