### ISSUE TITLE
Bug no points visible and missing point size option

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#140]
@arunge I tried loading a couple of datasets with coordinates via the Pandora import in the Iso beta app and no points are visible in the map. Funny enough, if I select the cluster option this works.

Also, the option to select point size has been removed. This should be placed back again. The user will be able to choose a point size by a field or a fixed size for all. Imagine the situation where the user does not want to select a field to define point size. How would then the point size be changed?

The same applies to all other point options (e.g. colour, etc)! Users can select to define these by a field or select a value for all options.

**Comment by arunge** [comment]
Regarding
> Also, the option to select point size has been removed. This should be placed back again. The user will be able to choose a point size by a field or a fixed size for all.

The point size was not removed, it is just hard to find (1). Should I shift it higher to the place where one can set the colour and symbol of location marks (2)?

| point size | colour and symbol|
|---|---|
|![image](https://user-images.githubusercontent.com/16759098/233914104-012fdc10-1bd3-4de4-ac0a-5e9286b10e05.png)|![image](https://user-images.githubusercontent.com/16759098/233914911-3ec01684-2f90-4a69-a909-1271ed40c8c3.png)|

Regarding:
> Imagine the situation where the user does not want to select a field to define point size. How would then the point size be changed?

There is a slider to change the point size for all points (3). One can find it below the option to set colour and shape (4).
To change the colour for all points, use "fixed" (5).
There is no option to change the symbol by a selected coumn, symbols are always set for all points.

| point size for all points | colour for all points |
|---|---|
|![image](https://user-images.githubusercontent.com/16759098/233916384-6e971692-a141-4f2c-bd5a-849bc9ba76bc.png)|![image](https://user-images.githubusercontent.com/16759098/233917697-74b4c25d-f849-4f03-a17d-124254f9e20b.png)|

I would really recommend to shift all the options to change the look of symbols to one place to remove the confusion. 
In the modelling tabs, the options named above are available for:

![image](https://user-images.githubusercontent.com/16759098/233914440-734a76ed-3950-4c93-b0af-bb4f3f7964c7.png)

**Comment by arunge** [comment]
Regarding

> I tried loading a couple of datasets with coordinates via the Pandora import in the Iso beta app and no points are visible in the map. Funny enough, if I select the cluster option this works.

After **uploading data within a modelling tab** (1), a map is only created after a model was run. That is, there is no automatic trigger to show a map that contains only data points but no model output. So, one always has to run a model before one can see a map.

I am not sure what situation had happen above, but when I tested 
- first uploading data and than running a model without a cluster option selected (2), points were visible on the map (3).
- first uploading data, selecting a cluster option and not pressing "Start", points were not visible on the map.

| After pressing "Start" | Before pressing "Start" |
|---|---|
|![image](https://user-images.githubusercontent.com/16759098/233921015-4245194a-ba0f-46e0-84ea-2644a922cfef.png)|![image](https://user-images.githubusercontent.com/16759098/233921610-3aa0ca4f-ebcd-4e16-9f68-a1f3cb9345b6.png)|

**Comment by arunge** [comment]
@isomemo Which steps should we do here?
- Should I shift all the options to change the look of symbols to one place?  (see above)
- Should we implement the option to display an empty map with only data points visible directly after data was uploaded within a modelling tab?

**Comment by isomemo** [comment]
@arunge I was referring to the module for Pandora data import. After this, we have the map shown in "Interactive map". As for the options after modelling we can discuss these.

**Comment by arunge** [comment]
Regarding
> Also, the option to select point size has been removed. This should be placed back again. The user will be able to choose a point size by a field or a fixed size for all. Imagine the situation where the user does not want to select a field to define point size. How would then the point size be changed?
>
> The same applies to all other point options (e.g. colour, etc)! Users can select to define these by a field or select a value for all options.

This was fixed within:
- https://github.com/Pandora-IsoMemo/iso-app/issues/13#issuecomment-1531812083

Regarding
> I tried loading a couple of datasets with coordinates via the Pandora import in the Iso beta app and no points are visible in the map. Funny enough, if I select the cluster option this works.

Could it be that the columns `Latitude` and `Longitude` had not been set correctly? If they are missing or the coordinate format is not correct, points will not be draw on the interactive map.

**Comment by arunge** [comment]
Issues had been reported and fixed [here](https://github.com/Pandora-IsoMemo/iso-app/issues/161).
