### ISSUE TITLE
Issue with Docker Installation

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/iso-app#142]
For the latest local version of IsoMemo, there is a problem with the API. I attach a screenshot.
![WhatsApp Image 2023-04-26 at 15 03 08](https://user-images.githubusercontent.com/101706974/234583731-12f2bdd8-23be-4287-ae43-fa3d5358dc46.jpeg)

@arunge

**Comment by arunge** [comment]
@jan-abel-inwt Please let us discuss this error tomorrow.

**Comment by jan-abel-inwt** [comment]
Sorry for the problem. We are working on the API right now.

For now you can fix this by giving the docker image the right environment variable
in the docker run command:

`docker run -p 3838:3838 -e API_BASE_URL=https://isomemodb.com/testapi/v1/ ghcr.io/pandora-isomemo/iso-app:main`

**Comment by arunge** [comment]
@CarloCocozza we added a default API_BASE_URL to the app that is used if no external parameter is submitted. This fix is available
- with version [23.04.1.6](https://github.com/Pandora-IsoMemo/iso-app/pull/146) on [main](https://isomemoapp.com/app/iso-memo-app) and
- with version 23.04.3.3 on [beta](https://isomemoapp.com/app/iso-memo-app-beta).

With the new versions you can use the normal docker command that is mentioned in the [wiki](https://github.com/Pandora-IsoMemo/iso-app/wiki/Local-install-instructions#3-run-the-application-in-docker) again.
