### ISSUE TITLE
Map points lo longer visible

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#148]
@arunge map points no longer visible in "Interactive map" of main isoapp version. See this video: https://www.youtube.com/watch?v=ptxxbsMT7ew

**Comment by arunge** [comment]
Please note
- https://github.com/Pandora-IsoMemo/iso-app/issues/144#issuecomment-1541531449

to check how this was solved.

**Comment by isomemo** [comment]
@arunge I am not sure what I am supposed to do here.

**Comment by arunge** [comment]
@isomemo That was only a note for us for documentation reasons.
