### ISSUE TITLE
Can no longer run AverageR modelling

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#17]
When trying to run an AverageR model I now get this error "
NA Site ID variable. Please check your data". This was working previously! Given the recent issue and SpreadR, perhaps several other things stopped working on this app?

**Comment by arunge** [comment]
@isomemo Maybe this was related to the fix in #16 

I tested AverageR with some data, it workes:

![image](https://user-images.githubusercontent.com/16759098/160361453-b6b398b0-d195-48dc-bfe1-f4011eeeabe4.png)

Could you check, and if the issue still exist, tell us exactly which inputs you used?

**Comment by isomemo** [comment]
Working now!
