### ISSUE TITLE
Bug in point display

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#193]
@arunge the option "Show locations on map" for model TimeR is no longer working. No points are shown when the checkbox is ticked.

**Comment by arunge** [comment]
@isomemo With [version 23.10.3](https://github.com/Pandora-IsoMemo/iso-app/pull/195) the issue with missing points in TimeR and KernelTimeR should be fixed now on [main](https://isomemoapp.com/app/iso-memo-app) and on [beta](https://isomemoapp.com/app/iso-memo-app-beta).
