### ISSUE TITLE
SVG export not working

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#194]
@arunge the SVG export for plots created in TimeR is no longer working. I suspect that the same applies to other models but did not have the time to try.

**Comment by arunge** [comment]
@isomemo Unfortunately, I need some more details regarding this issue. 

Simply with the online test model I could not reproduce the bug.
I tested the main and the beta version locally in RStusio and with Chrome and Firefox. The `svg` export was working as expected.

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/f97a5bed-1b60-413a-9c72-3a90944b6a42)
![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/ae1fd746-40de-45e6-a63b-d80d245bbdb7)

Do you remember which settings you used? Did you apply particular plot options before the export?

**Comment by isomemo** [comment]
@arunge I also cannot reproduce the error, so let's close this! If it happens again, I will try to record the exact conditions.
