### ISSUE TITLE
Issue with Location Marks in TimeR

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/iso-app#200]
Whenever I use TimeR, the outcome of the model shows all location marks on map. However, only location marks of sites that are modelled for the timeslice that is shown should appear.
I am not sure, but was not there an option in the past for this? I.e. deciding whether showing all the location marks of the uploaded dataset or only those that are pertinent to the specific time-slice that one is looking at.

I attach a dataset for reference:  [Filtered Dataset for Modelling (Humans).xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/14650505/Filtered.Dataset.for.Modelling.Humans.xlsx)

And its model: [2024-03-19_13-39-16_model_TimeR.ZIP](https://github.com/Pandora-IsoMemo/iso-app/files/14650620/2024-03-19_13-39-16_model_TimeR.ZIP)

@arunge @mgross

**Comment by arunge** [comment]
@CarloCocozza Do you mean following option?

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/3e079b4e-22f0-49ab-9647-dea0dd2688eb)

When playing around with this option the estimates change but not the displayed points:

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/b30d98aa-8cfa-43f3-a134-075f401269ab)
![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/afae3168-3449-49e7-beef-6ca1ef5a37d9)
![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/59c9b817-ad27-4ae5-81c5-e19fa7f8bc01)

There is a filter for choosing the data points to be displayed: 

https://github.com/Pandora-IsoMemo/iso-app/blob/41ad0305c8bf1dcb56a11d5530915d6bb2fb0658/R/01-plotMap.R#L2756C1-L2759C2

Maybe this is not working as expected.

@CarloCocozza to be clear, you would expect, when choosing "time-sliced spatial" the [time filter](https://github.com/Pandora-IsoMemo/iso-app/blob/41ad0305c8bf1dcb56a11d5530915d6bb2fb0658/R/01-plotMap.R#L2756) should be applied?

If so, I can check if there is missing something when "time-sliced spatial" is selected.

**Comment by CarloCocozza** [comment]
Hi @arunge, 

the convex hull should indeed impact the estimates, which it does. The issue is with the appearance of location marks, and this should have a separate filtering option.

In the past, TimeR only showed by default location marks of sites that were taken into account for the specific temporal model that is selected (e.g. 800 - showing sites that are present at 800 CE). This happened regardless of the convex hull option that was selected. 

Whereas now, location marks of all sites included in the original uploaded file are shown in any temporal model (e.g. -2000; -1000; 500; 1500 etc.), despite their presence in the selected time.

**Comment by arunge** [comment]
@CarloCocozza The issue with the time filter for location marks is fixed with [version 24.04.1](https://isomemoapp.com/app/iso-memo-app) on [iso app main](https://isomemoapp.com/app/iso-memo-app) and with version 24.05.0.1 on [beta](https://isomemoapp.com/app/iso-memo-app-beta).

Regarding
> I am not sure, but was not there an option in the past for this?

I checked the code, there never was an option in TimeR, but this was the default behaviour. However, there is an option to display points for all times when using clusters in KernelTimeR. Maybe this is what you meant?

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/cc48dfc8-df03-4a4f-8b81-5d3445fb0a06)

Since the bug is fixed I am closing here.
