### ISSUE TITLE
Error trying to load https://pandorasearch.earth/

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#201]
@arunge when entering the address https://pandorasearch.earth/ got this error:

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/46485054/1f9fd184-e75a-4a8d-8628-191d6f45351d)

**Comment by arunge** [comment]
Currently I can access the address: https://pandorasearch.earth/
Probably there was maintenance on the server.

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/7ad5feb7-79de-4805-85d4-9c2389d14b0c)
