### ISSUE TITLE
TimeR stopped running models

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#28]
TimeR models get stuck early on. Using this dataset: 
[combined fauna2.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/8539517/combined.fauna2.xlsx)

and model settings and bug shown in this video: https://youtu.be/_C2kZQP8PbA

The models have now been stuck for a very long time (usually takes 1 minute to run this dataset) and it might be related to the previous bug: #27

**Comment by jroachell15** [comment]
@isomemo hi Ricardom

I have tried to reproduce this bug and was not successful on the beta version. The data you provided worked for me with all the conditions you provided in the youtube video. Here are the results:

![image](https://user-images.githubusercontent.com/73887426/165472078-cf1bf962-aaac-4096-8458-78861880243d.png)

Please try again on your side, and please let me know if you have other issues with it. thanks!

**Comment by isomemo** [comment]
Working now!
