### ISSUE TITLE
Text updates for IsoMemo CRAN package

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#38]
Requests for text edits to the description of the package (in the webpage and in the pdf):

Where it says "Retrieve Data using the Max Plank Institute 'IsoMemo' API" please change this to
 
"Retrieve Data using the 'IsoMemo' API". This is in the pdf and in the title of the webpage.

Where it says"database options: "14CSea" , "IntChron" , "IsoArcH" , "LiVES" change to
 
"examples of database options: "14CSea" , "IntChron" , "CIMA" , "LiVES"

Where it says "Data retrieval for the IsoMemo App Project https://isomemoapp.com/ Given the parameters Database
name, category names, and field names."

change to

"Data retrieval for databases within the IsoMemo initiative (https://isomemo.com/). Given the parameters Database
name, category names, and field names."

**Comment by jroachell15** [comment]
@isomemo changes are made, and now going under review. updates are coming.

**Comment by jroachell15** [comment]
Today we have submitted these changes to CRAN. @isomemo

**Comment by jroachell15** [comment]
@isomemo 

Spelling and names are changed for IsoMemo Package:

see: https://cran.r-project.org/web/packages/IsoMemo/IsoMemo.pdf

and https://cran.r-project.org/web/packages/IsoMemo/index.html
