### ISSUE TITLE
[FOR ALL MPI APPS ]: Use of frames to make the interfaces easier to navigate (1,5 days)

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#4]
Original ticket: https://github.com/INWT/mpi-resources/issues/401

All apps (current and future): use of frames to make the interfaces easier to navigate. At the moment model/graphical options are in the same frame as the results output (e.g. maps) and when one has to scroll down model/graphical options the output is no longer visible. Frames should be used for all apps to separate different input/output sections (e.g. separating data options on opposing sides of the app and these from the results display, so that the latter are always visible).

- IsoMemo/Pandora
  - [ ] main*
  - [x] beta
- ReSources
  - [ ] main*
  - [x] beta
- [x] Bpred
- OsteobioR
  - [ ] main*
  - [x] beta
- BMSC
  - [ ] main*
  - [x] beta
- PlotR
  - [x] main
  - [x] beta

* Will be available with the next deployment from beta to main after other updates were approved, e.g. the new import module.

**Comment by arunge** [comment]
- https://community.rstudio.com/t/shiny-mainpanel-locking/51700
- https://stackoverflow.com/questions/43972650/make-sidebarpanel-autoscroll-with-mainpanel-in-shiny
- https://stackoverflow.com/questions/56407601/how-to-fix-the-position-of-main-panel-in-r-shiny

**Comment by arunge** [comment]
With [version 23.01.1](https://github.com/Pandora-IsoMemo/iso-app/pull/87#issue-1530898620) on [isomemo app beta](https://isomemoapp.com/app/iso-memo-app-beta) I added auto scroll into the sidebars.

**Comment by arunge** [comment]
Regarding:
> works only with one (left) sidebar, because padding gets lost

On must specify `height` instead of `max-height`:

```R
style = "position:fixed; width:15%; max-width:350px; overflow-y:auto; height:85%",
```

With [BPred version 23.01.2](https://github.com/Pandora-IsoMemo/bpred/pull/18) I added auto scroll to the sidebars. Online : https://isomemoapp.com/app/bpred

**Comment by arunge** [comment]
The `auto scroll` feature is available in all beta versions of the apps. When updating the main versions (after testing new features of the respective apps) it will be available in all apps. So, all is done here.
