### ISSUE TITLE
Check is failing on beta branch

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#49]
With the last [commit on the beta branch](https://github.com/Pandora-IsoMemo/iso-app/commit/d940e9ac1565a6e387532ddf3f484ce1dab3496b) now the check is failing:

```R
> checking R code for possible problems ... NOTE
  modelAssignRMC: no visible binding for global variable ‘x’
  Undefined global functions or variables:
    x
```

@mgross Could you please fix this?
And could you please open a pull request the next time before merging into the branch? Then it is easier to see that checks fail. :wink: 
Thanks in advance! :slightly_smiling_face:

**Comment by arunge** [comment]
@mgross Could you please check why the test is failing? I would like to merge the current beta into the main branch **before** adding new options regarding https://github.com/Pandora-IsoMemo/iso-app/issues/37 to the beta branch.

**Comment by mgross** [comment]
fixed

**Comment by arunge** [comment]
Thanks!
