### ISSUE TITLE
[MPI_WP2]: 1. Github and documentation

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#51]
- [x] Migration of all codes to Github repositories. The service provider will be provided with existing code from c. 10 different Shiny apps/R packages and will migrate these to individual repositories within the GitHub Pandora &
IsoMemo software platform (https://github.com/Pandora-IsoMemo)
- [ ] https://github.com/Pandora-IsoMemo/shiny-tools/issues/1: Document in a CRAN style all inputs for function(s) called when an app model is executed plus the raw outputs (no documentation for display options). This requires extensive familiarity with Bayesian modelling. As part of the Github documentation for each app there should be two pdf files with permanent name/location within the corresponding GitHub repository. Such pdf files are subject to future updates and provide
  - a _brief description of the app_ and 
  - _help information_. 
  - In each app there will be two interface buttons (**“About”** and **“Help”**) that when pressed display each of the pdfs.
  - When applicable, for existing apps, 
    - the button “Cite” should be renamed **“About”**. When applicable, 
    - the existing button **"Help"** is kept in place but add to the left of these three 
    - other buttons that open the following websites in new tabs:
      - **“Data search”** https://pandorasearch.earth/
      - **“Pandora”** pandora.earth
      - **“IsoMeMo”** isomemo.com
  - for this, modularize (-> _DataTools_) and apply the same UI in all apps:
 
|Isomemo App / Bpred |ReSources |OsteoBioR | BMSC / PlotR |
|---|---|---|---|
|![image](https://user-images.githubusercontent.com/16759098/217188413-91cb4cfe-7b25-4262-8de6-c4c5b0d925a1.png)|![image](https://user-images.githubusercontent.com/16759098/217188528-20ddfd59-eed2-47e9-baf2-4f392015c894.png)|![image](https://user-images.githubusercontent.com/16759098/217189228-4a903359-e0c3-430d-a949-499bb1f49f06.png)|![image](https://user-images.githubusercontent.com/16759098/217189642-0b1a6bdc-a9d5-466f-934b-0f44d766e225.png)|
- [ ] Name and logo’s for each app to be updated following given instructions.
- [x] https://github.com/Pandora-IsoMemo/iso-app/issues/169: For the different spatial results obtained via the IsoMemo app one can calculate a mean value for a specific location. Currently the user only needs to introduce coordinates and this is automatically shown and cannot be hidden again. Include the pixel size value in the estimated text. This is applicable to the following models: AverageR, TimeR, SpreadR, KernelR, KernelTimeR, and OperatoR as displayed here: https://isomemoapp.com/app/iso-memo-app The figure below exemplifies the inputs and how these are to be modified.

![Image](https://user-images.githubusercontent.com/73887426/183862098-d498214c-f383-431c-a626-7d1fe4fb94b9.png)

**Comment by arunge** [comment]
Continuation within:
- https://github.com/Pandora-IsoMemo/shiny-tools/issues/1

I am closing here
