### ISSUE TITLE
[MPI_WP2]: 8. All apps provided as part of GitHub transfer

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#55]
- Add option to store only data and model input parameters without the model output
plus optional results. These are the examples to be uploaded to a certain directory and
will populate a pending list in the app and the user can select and load one of these.
  - [x] [BMSC App](https://github.com/Pandora-IsoMemo/bmsc-app)
    - https://github.com/Pandora-IsoMemo/bmsc-app/pull/21
  - [x] [BPred](https://github.com/Pandora-IsoMemo/bpred): -> https://github.com/Pandora-IsoMemo/bpred/issues/1
    - _done:_ store inputs only
    - _done:_ load models directly from github
  - [x] [OsteoBioR](https://github.com/Pandora-IsoMemo/osteo-bior)
    - _done:_ store inputs only
    - https://github.com/Pandora-IsoMemo/osteo-bior/pull/22
  - [x] [Iso App](https://github.com/Pandora-IsoMemo/iso-app)
    - store / load models -> https://github.com/Pandora-IsoMemo/iso-app/issues/3
  - [x] [PlotR](https://github.com/Pandora-IsoMemo/plotr)
    - https://github.com/Pandora-IsoMemo/plotr/pull/30
  - [x] [ReSources](https://github.com/Pandora-IsoMemo/resources)
    - _done:_ store inputs only
    - https://github.com/Pandora-IsoMemo/resources/pull/89
- [x] Pandora-IsoMemo/iso-app-tools#1
Modularize the Import Data interface from the Pandora skin. Make this the interface for all data inputs across the different app. Ensure that any data checks made by the different app (e.g., checking if values are numeric) are kept in place.
- [x] Implement local installer using Docker

**Comment by arunge** [comment]
@isomemo With merging the pull requests:
- https://github.com/Pandora-IsoMemo/iso-app/pull/128
- https://github.com/Pandora-IsoMemo/bmsc-app/pull/23

I could add the feature for model up- and download to the last two apps. Now, for all apps it is possible to store either 
 - user inputs, data and model output, or
 - only user inputs and data,

Additionally, I also finished to link the .zip files for predefined models (currently test models) directly to the respective folder on github for each of the apps . That means, uploading a .zip file into this folder makes the .zip file available in the select menu for online models, one only has to reload the browser.

![image](https://user-images.githubusercontent.com/16759098/230033624-d7958d71-634c-41f6-82d0-28f981ee0748.png)

The link to the folder for predefined models was added to each of the README's. You can now start adding models by just uploading them into the folder.

Please let me know if you experience unexpected behavior! Happy testing! :slightly_smiling_face:

**Comment by arunge** [comment]
All above was implemented. There was an update of the task regarding how data and models should be uploaded:
- https://github.com/Pandora-IsoMemo/data-tools/issues/50

Following issues are discussed in that ticket.
