### ISSUE TITLE
[MPI_WP2]:Further suggestions for IsoMemo

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#56]
**Suggestion of further features: 

Isomemo App - Saved Maps tab:** 
from https://github.com/Pandora-IsoMemo/iso-app/issues/20
Under the main menu currently named "Saved maps" I can create new numeric maps. If I select the option region-circle, I can select to create a numeric map for a certain radius around a certain centre. This seems to be Ok. However, if I select the option region-square the options are the same. This should be renamed as region-rectangle. Here, the options should be the upper left/lower right corners of the rectangle area to defined with respective lat/long inputs.

**Comment by arunge** [comment]
This is part of task: 
- https://github.com/Pandora-IsoMemo/iso-app/issues/69#issue-1404326437

and was developed within 
- https://github.com/Pandora-IsoMemo/iso-app/issues/19#issuecomment-1385662041

and is now under review. I close here.
