### ISSUE TITLE
Bug in updating Interactive map

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#63]
@arunge 

I loaded LiVES data and produced a map via the Interactive map tab. This is working fine.

I then applied a filter to the data table which reduced the number of points to be shown on the map. However, the Interactive map did not update the point display. It kept displaying all of the points from the first map rendering. Interestingly, I changed point size and this was only applied to filtered data points.

**Comment by arunge** [comment]
@isomemo Could you tell me (or give me a screenshot) where you specified the filter, that is, which input did you use for filtering?

**Comment by isomemo** [comment]
@arunge the fastest method would be to apply filters to the lat/long fields

![image](https://user-images.githubusercontent.com/46485054/194008080-01683102-0255-4b0d-9cac-b50fc14775f5.png)

I changed the point size and as you can see below the pre-filter points are still shown

![image](https://user-images.githubusercontent.com/46485054/194008310-de09d443-78d5-41ac-bd69-e0ed0e72a01b.png)

Also, some time ago we discussed that the point size looks different for different parts of the world. Looking at the map it also seems that this is still not working properly.

**Comment by arunge** [comment]
I merged a [new version 22.10.1](https://github.com/Pandora-IsoMemo/iso-app/pull/66#issue-1398179557) to the [beta app](https://isomemoapp.com/app/iso-memo-app-beta) that fixes the bug with the filter. 

The [issue with the point sizes is still open](https://github.com/Pandora-IsoMemo/iso-app/issues/44).
