### ISSUE TITLE
Text labels for LocateR

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#64]
@arunge 

Update texts for the LocateR interface:

![image](https://user-images.githubusercontent.com/46485054/193861309-74b5ad4c-0fa2-41ad-9ff9-ac75387e05ff.png)

"Data source" should be "Options"

"Select maps for similarity map:" should be "Select baseline maps:

**Comment by arunge** [comment]
@isomemo I have not noticed this issue for a while. Sorry for this! Is the mentioned renaming from above still up-to-date?

**Comment by arunge** [comment]
On its way through automatic tests. Will be available online with versions:
- 23.04.1.3 on [iso-app main](https://isomemoapp.com/app/iso-memo-app)
- 23.04.2.1 on [iso-app beta](https://isomemoapp.com/app/iso-memo-app-beta)
