### ISSUE TITLE
Pandora Skin: automatically set Longitude and Latitude fields after loading data

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#67]
For Pandora skin, currently users have to manually select longitude and latitude fields. This should remain possible. However, now when selecting a data resource the app will check if there are fields named Longitude or Long and Latitude or Lat. If so, these are automatically assigned.

**Comment by arunge** [comment]
I merged a [new version 22.10.1](https://github.com/Pandora-IsoMemo/iso-app/pull/66#issue-1398179557) to the [beta app](https://isomemoapp.com/app/iso-memo-app-beta) that contains this feature.

@isomemo Feel free to test it and let me know if all is done here.

**Comment by isomemo** [comment]
@arunge I tried it with this test file: 
[test.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10140224/test.xlsx)

An error was issued that coordinates had the wrong format although the app went on to create the table. It did so by adding two additional longitude and latitude fields to the table:

![image](https://user-images.githubusercontent.com/46485054/205271637-2ea26546-e7fe-4a3b-934e-ce3eeaa5d48f.png)

Is it supposed to work like this?

**Comment by arunge** [comment]
@isomemo With [version 22.12.2](https://github.com/Pandora-IsoMemo/iso-app/pull/84#issue-1503179829) on the [isomemo app beta](https://isomemoapp.com/app/iso-memo-app-beta) I added a notification if lng/lat conversion was successful and that "longitude"/"latitude" columns where set.

That is,
- if successful, than "longitude"/"latitude" columns are added and original lng/lat columns are removed or overwritten. 
- when (e.g. after switching around) format conversion fails, columns "longitude"/"latitude" are removed and the original lng/lat columns are added again.

If the format is changed, there will be a new notification each time. 
Only if "longitude"/"latitude" columns exist in the data, they will be displayed in the map and available in modelling.
