### ISSUE TITLE
Certificate warning

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#68]
@wahani @arunge 

The following certificate related message is shown when trying to access isomemosearch.com

![image](https://user-images.githubusercontent.com/46485054/194282629-37d33e80-4698-47e2-93ef-4553685a0221.png)

**Comment by wahani** [comment]
@isomemo the certificates are issued by the MPI IT. I will reach out to them and bring this to their attention.

**Comment by isomemo** [comment]
@wahani thank you!

**Comment by wahani** [comment]
I just checked. There is already a new certificate in place. We can close this issue then, nothing more to do.
