### ISSUE TITLE
Provide code for HTML interface

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#79]
@isomemo asked for the code for the html page:

> 3) Please send me the code for the html interface where we can select apps (https://isomemoapp.com/) so that our designers can update it. If this is truly only html code our designers can download it directly and send back the modified version. Please let me know!

@jan-abel-inwt could you check where the code can be found? @wahani mentioned it must lie somewhere on the shinyproxy server. If you have questions, please ask @wahani.

Let me know, when you found the code. Thanks! :slightly_smiling_face:

**Comment by jan-abel-inwt** [comment]
The code can be found on the `mpi-iso-app` machine under  `/etc/shinyproxy/templates/2col`

```
├── assets
│   ├── css
│   │   └── 2-col-portfolio.css
│   └── img
│       ├── bpred.png
│       ├── iso-memo-app.png
│       ├── iso-memo-data-app.png
│       ├── mpi-iso-app-test.png
│       ├── osteo-bio-r.png
│       └── resources.png
├── error.html
└── index.html

```

**Comment by arunge** [comment]
@isomemo Does your IT need more details on how to find the code or the given path [above](https://github.com/Pandora-IsoMemo/iso-app/issues/79#issuecomment-1332023559) enough?

**Comment by arunge** [comment]
finished
