### ISSUE TITLE
IsoMemo App: Deploy changes from beta to the main app

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#80]
I would like to merge the current beta version into the main version. This would add **all** changes from version 22.09.1 on (documented [here](https://github.com/Pandora-IsoMemo/iso-app/blob/beta/NEWS.md#mpiisoapp-22091)) to the [main app](https://isomemoapp.com/app/iso-memo-app), including Bug fixes for 
- #62, 
- #63, 
- #67, 
- #44, 
- #27. 

Is that ok for you?

Afterwards, I would start adding features regarding the [merging of files](https://github.com/Pandora-IsoMemo/iso-app/issues/37) into the beta version, such that you can test those features and that we can discuss how to implement open points regarding the merging in a future meeting.

_Originally posted by @arunge in https://github.com/Pandora-IsoMemo/iso-app/issues/27#issuecomment-1306857463_
      
----

Note: There are new features that you did not confirm yet (the issues are assigned to you): 
- #8, 
- #67,
- #27

Should we wait with merging those into the main app until you had the time to test them?

_Originally posted by @arunge in https://github.com/Pandora-IsoMemo/iso-app/issues/27#issuecomment-1306919668_

**Comment by isomemo** [comment]
@arunge please merge!

**Comment by arunge** [comment]
Ok, Isince the two open tasks (#8, #67) are almost done, I will wait for them.

**Comment by isomemo** [comment]
@arunge I could not test this. I loaded the Lives dataset and tried the SpreadR model (Beta) with the default settings using the fields DateLower and DateUpper as the date range. I have used this multiple times for testing purposes. This time the app got stuck running chain 1. I tested this twice.

**Comment by isomemo** [comment]
@arunge @mgross Marcus, I just want to be certain that the speed calculations vary due to pixel size. Is this correct? This would solve the issue since Antonia will add to the results pixel size.

**Comment by arunge** [comment]
@isomemo Since all issues are closed from [above](https://github.com/Pandora-IsoMemo/iso-app/issues/80#issue-1452927249), I released the newest version 22.12.3 from the beta app also on the [isomemo main app](https://isomemoapp.com/app/iso-memo-app).
