### ISSUE TITLE
Create wiki with installation instruction

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#82]
Move and update installation instructions from 
- https://github.com/Pandora-IsoMemo/drat/issues/3

to a new created wiki of this app

**Comment by jan-abel-inwt** [comment]
https://github.com/Pandora-IsoMemo/iso-app/wiki/Getting-Started

This works fine on my machine

```
Machine     -  Dell Inc. Latitude 7400                
Kernel      -  6.0.6-76060006-generic                 
Distro      -  Pop!_OS 22.04 LTS                      
DE          -  Pop:GNOME         
```
