### ISSUE TITLE
Detect duplicates for user selected fields

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#88]
Method to detect duplicates for user selected fields (user would select fields and define level of similarity for both numeric and text fields). User is then given then the option to visualize/export data table with just the duplicates or with duplicates removed (only one row of duplicates is shown).

**Comment by arunge** [comment]
Note: Following functions that are already defined in the package might help for developing this feature. They can be used to identify numeric or non-numeric columns:

https://github.com/Pandora-IsoMemo/iso-app/blob/main/R/01-fieldTypes.R

**Comment by arunge** [comment]
> - [ ] **Duplicate search:** Users would be able to select fields of interest for duplicate identification from the Pandora skin within the IsoMemo app (https://github.com/Pandora-IsoMemo/iso-app/tree/main/R). In terms of matching options the user may select an exact match or if a string in one cell is contained within another. If the search should be case sensitive or not and if spaces should be considered or not. In terms of display, the user may select to add a new column where duplicates are flagged or only to display the first or last duplicate.
> Duplicate search within IsoMemo: similar to above for the IsoMemo skin (see text above).

_From https://github.com/Pandora-IsoMemo/iso-app/issues/69#issue-1404326437_

Relevant here: In terms of matching options the user may select 
- [x] an exact match or 
- [ ] if a string in one cell is contained within another. 
- [x] If the search should be case sensitive or not and 
- [ ] if spaces should be considered or not

**Comment by arunge** [comment]
@isomemo With [isomemo-app version 23.03.3](https://github.com/Pandora-IsoMemo/iso-app/pull/114) on [beta](https://isomemoapp.com/app/iso-memo-app-beta), the option to keep the last / first match was added.

So all is done here. Feel free to test the new features!

**Comment by isomemo** [comment]
@arunge we should discuss how I can test this

**Comment by arunge** [comment]
@isomemo I checked if the rounding with negative numbers is working. It does! Happy testing! :slightly_smiling_face: 
Please let us know if you want to change the text!

---

I chose "Lives" and selected:
- langitude: "exact match"
- longitude: "exact match"
- d13C: "rounded match"

## Rounding factor 1 and show only duplicates:

![image](https://user-images.githubusercontent.com/16759098/225616833-d452f69f-5851-45cb-b508-bbd9b26cd79f.png)

## Rounding factor -1 and show only duplicates:

![image](https://user-images.githubusercontent.com/16759098/225617673-18172cab-8760-476c-8376-bdcf75b704f6.png)

**Comment by arunge** [comment]
@isomemo The task is finished. Feel free to test at any time and open a new ticket if you observe any issues. I am closing here.
